version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTHRE_ISER: postgres
      POSTGRES_DB: review
      POSTGRE_PASSWORD: password

  redis:
    image: redis
    ports:
      - '6379:6379'